### ISSUE TITLE
Request permission before use

### ISSUE THREAD

**Issue by notafish** [uwc/uwcde-website#1]
Hallo Connor, nur eine Kleinigkeit. Entweder ist das Theme Open Source, oder es ist es nicht. Wenn es tatsächlich Open Source ist, dann soll man kein "permission" frage sollen. ;) Soweit ich sehen kann, die MIT license ist sehr klar. "Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software". Ich würde das umschreiben in: "We would be grateful if you contacted us if you're using this theme". Oder so was in der Art.

**Comment by connor-baer** [comment]
Hi Delphine, vielen Dank für den Anstoß! Bisher hatte ich mir keine genaueren Gedanken zur Lizenz gemacht. 
Ich habe die Lizenz zu [GPL-3.0](https://github.com/uwc/uwcde-website#copyright) geändert, so wie es von [WordPress gewünscht ist](https://developer.wordpress.org/themes/getting-started/wordpress-licensing-the-gpl/). Bei der Gelegenheit habe ich auch die README Dateien aktualisiert und erweitert.
